// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The pooled DATABASE_URL (PgBouncer) doesn't hold the session-scoped
    // advisory lock `prisma migrate deploy` needs, causing build-time P1002
    // timeouts. The direct/unpooled URL avoids that; fine for this app's
    // low, single-team traffic.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
